/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fpl_ffmpeg_Manager */

#ifndef _Included_org_fpl_ffmpeg_Manager
#define _Included_org_fpl_ffmpeg_Manager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fpl_ffmpeg_Manager
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fpl_ffmpeg_Manager_createEngine
  (JNIEnv *, jobject);

/*
 * Class:     org_fpl_ffmpeg_Manager
 * Method:    playStream
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_fpl_ffmpeg_Manager_playStream
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_fpl_ffmpeg_Manager
 * Method:    shutdownEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fpl_ffmpeg_Manager_shutdownEngine
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
