/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fpl_media_MediaPlayer */

#ifndef _Included_org_fpl_media_MediaPlayer
#define _Included_org_fpl_media_MediaPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fpl_media_MediaPlayer
 * Method:    n_createEngine
 * Signature: (Ljava/lang/ref/WeakReference;)V
 */
JNIEXPORT void JNICALL Java_org_fpl_media_MediaPlayer_n_1createEngine
  (JNIEnv *env, jobject obj);

/*
 * Class:     org_fpl_media_MediaPlayer
 * Method:    n_setDataSource
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_fpl_media_MediaPlayer_n_1setDataSource__Ljava_lang_String_2
  (JNIEnv *env, jobject obj, jstring path);

/*
 * Class:     org_fpl_media_MediaPlayer
 * Method:    n_setDataSource
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_fpl_media_MediaPlayer_n_1setDataSource__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *env, jobject obj, jstring path, jstring format);

/*
 * Class:     org_fpl_media_MediaPlayer
 * Method:    n_playStream
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fpl_media_MediaPlayer_n_1playStream
  (JNIEnv *env, jobject obj);

/*
 * Class:     org_fpl_media_MediaPlayer
 * Method:    n_stopStream
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fpl_media_MediaPlayer_n_1stopStream
  (JNIEnv *env, jobject obj);

/*
 * Class:     org_fpl_media_MediaPlayer
 * Method:    n_shutdownEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fpl_media_MediaPlayer_n_1shutdownEngine
  (JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
